name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: ".github/**"
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Semantic Versioning
        uses: PaulHatch/semantic-version@v5.0.3
        id: semantic_version
        with:
          tag_prefix: "v"
          major_pattern: "feat:"
          minor_pattern: "fix:"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            esyfyi/esy-state-site:${{ steps.semantic_version.outputs.version_tag }}
            
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: docker.io/esyfyi/esy-state-site:${{ steps.semantic_version.outputs.version_tag }}
          service: esy-state-site
